// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eigckzqzognxoesgisle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpZ2NrenF6b2dueG9lc2dpc2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzM3MzUsImV4cCI6MjA2NjQwOTczNX0.lXAS24Zd3eUoFR5Bi33cLGYkzucclomeDx6GUUCbOCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);